
name: Foresight CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Add XunitXML dependency
      run: |
        regex='PackageReference Include="([^"]*)" Version="([^"]*)"'
        find . -name "*.*proj" | while read proj
        do
          while read line
          do
            if [[ $line =~ $regex ]]
          then
            name="${BASH_REMATCH[1]}"
            version="${BASH_REMATCH[2]}"
            if [[ $version != *-* ]]
            then
              dotnet add $proj package XunitXml.TestLogger --version 3.0.70
            fi
          fi
          done < $proj  
        done

    - name: Test
      run: dotnet test ./src/GraphQL.sln --logger:xunit


    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: thundra-io/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
        test_framework: xunit2
        test_path: "./src/**/TestResults/**"
